### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by ahmadabudawod** [tagyro/AMLocalizedString#2]
Is there a Swift version of this library until now ?

**Comment by tagyro** [comment]
Not yet, although you can use the objective-c version in a swift project. 
If you use CocoaPods, be sure to add `use frameworks` in your podfile and `pod 'AMLocalized', '~> 0.3'` to use the library.

**Comment by ghousesgb** [comment]
## I have used pod file as below

platform :ios, '8.0'
use_frameworks!

target 'MutliLanguage' do
pod 'AMLocalized', '~> 0.3'
end

---

Try 1:
import UIKit
import LocalizationSystem //Compiler Error: no such module

Try 2 : without import LocalizationSystem
override func viewDidLoad() {
        super.viewDidLoad()
        LocalizationSetLanguage() //Compiler Error 
} 

Could you kindly help me in finding the issue and what I am doing wrong?

**Comment by tagyro** [comment]
You have to
import AMLocalized
 then use the LocalizationSystem. ...
Let me know if you still have problems.

**Comment by ghousesgb** [comment]
Thanks for quick reply,
following are the changes made after import AMLocalized
LocalizationSystem.sharedLocalSystem().setLanguage("te-IN"); // this is working fine.
What I'm doing is right?
self.welcomeLabel.text   = LocalizationSystem.sharedLocalSystem().localizedStringForKey("Welcome", value: "Welcome")

above code doesn't change any language.

Here might be the issue
NSBundle </Users/sheikghose/Library/Developer/CoreSimulator/Devices/1F31B3BB-11C1-4299-8EAE-0F53A95CF6AB/data/Containers/Bundle/Application/4D9ECB49-E2C9-482F-ACF9-60777B0BDE4C/MutliLanguage.app/hi-IN.lproj> (not yet loaded)
where it shows not yet loaded.

**Comment by tagyro** [comment]
When you set the language, that .strings file must exist - does that file exist and does it have a value for "welcome" ?

**Comment by ghousesgb** [comment]
![screen shot 2016-01-06 at 10 29 30 am](https://cloud.githubusercontent.com/assets/1427049/12135377/de622bb0-b460-11e5-80c8-7d36b4e87a72.png)
Yes, I have .strings file and value set to Welcome, Kindly have a look to attachment.
Thanks
Ghouse

**Comment by ghousesgb** [comment]
![screen shot 2016-01-06 at 12 01 58 pm](https://cloud.githubusercontent.com/assets/1427049/12136409/513715cc-b46d-11e5-973e-88bcc14fb796.png)

The creating Localizable file has fixed my issue.
All is good, now.
You can close the issue.

Thanks
Ghouse

**Comment by tagyro** [comment]
Happy you solved this!
